# Generated by Django 3.0 on 2021-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=256)),
                ('stop_name', models.CharField(max_length=256)),
                ('stop_number', models.CharField(max_length=256)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Current_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('dt', models.DateTimeField()),
                ('route', models.CharField(max_length=8)),
                ('direction', models.CharField(max_length=32)),
                ('day', models.CharField(max_length=8)),
                ('leave_t', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('dt', models.DateTimeField()),
                ('trip_id', models.CharField(max_length=256)),
                ('route_id', models.CharField(max_length=256)),
                ('schedule', models.CharField(max_length=256)),
                ('start_t', models.CharField(max_length=256)),
                ('start_d', models.CharField(max_length=256)),
                ('stop_id', models.CharField(max_length=256, null=True)),
                ('delay', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField()),
                ('dt', models.DateTimeField()),
                ('weather_id', models.IntegerField()),
                ('weather_main', models.CharField(max_length=256)),
                ('coord_lon', models.FloatField()),
                ('coord_lat', models.FloatField()),
                ('weather_description', models.CharField(max_length=500)),
                ('weather_icon', models.CharField(max_length=256)),
                ('weather_icon_url', models.CharField(max_length=256)),
                ('base', models.CharField(max_length=256)),
                ('main_temp', models.FloatField()),
                ('main_feels_like', models.FloatField()),
                ('main_temp_min', models.FloatField()),
                ('main_temp_max', models.FloatField()),
                ('main_pressure', models.IntegerField()),
                ('main_humidity', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField()),
                ('clouds_all', models.IntegerField()),
                ('sys_type', models.IntegerField()),
                ('sys_id', models.IntegerField()),
                ('sys_country', models.CharField(max_length=256)),
                ('sys_sunrise', models.BigIntegerField()),
                ('sys_sunset', models.BigIntegerField()),
                ('timezone', models.BigIntegerField()),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('cod', models.IntegerField()),
            ],
        ),
    ]
