# Generated by Django 3.0 on 2021-08-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='main_feels_like',
        ),
    ]
