# Generated by Django 3.0 on 2021-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('dt', models.DateTimeField()),
                ('trip_id', models.CharField(max_length=256)),
                ('route_id', models.CharField(max_length=256)),
                ('schedule', models.CharField(max_length=256)),
                ('start_t', models.CharField(max_length=256)),
                ('start_d', models.CharField(max_length=256)),
                ('stop_id', models.CharField(max_length=256)),
                ('delay', models.IntegerField()),
            ],
        ),
    ]
