# Generated by Django 3.0 on 2021-08-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_timetable_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=8)),
                ('headsign', models.CharField(max_length=32)),
                ('day', models.CharField(max_length=8)),
                ('stop', models.CharField(max_length=8)),
                ('leave_t', models.CharField(max_length=32)),
                ('stop_time', models.CharField(max_length=32)),
                ('end_t', models.CharField(max_length=32)),
            ],
        ),
    ]
