# Generated by Django 3.0 on 2021-08-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0002_remove_currentweather_main_feels_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='weather_id',
        ),
    ]
