# Generated by Django 3.0 on 2021-08-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0002_current_timetable_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_timetable_all',
            name='stop',
            field=models.CharField(max_length=32),
        ),
    ]
