# Generated by Django 3.0 on 2021-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0002_currentbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbus',
            name='delay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currentbus',
            name='stop_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
