# Generated by Django 3.0 on 2021-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0003_auto_20210622_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=256)),
                ('stop_name', models.CharField(max_length=256)),
                ('stop_number', models.CharField(max_length=256)),
                ('stop_lat', models.CharField(max_length=256)),
                ('stop_lon', models.CharField(max_length=256)),
            ],
        ),
    ]
