# Generated by Django 3.0 on 2021-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0003_remove_currentweather_weather_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('dt', models.DateTimeField()),
                ('weather_main', models.CharField(max_length=256)),
                ('weather_description', models.CharField(max_length=500)),
                ('weather_icon', models.CharField(max_length=256)),
                ('weather_icon_url', models.CharField(max_length=256)),
                ('main_temp', models.FloatField()),
            ],
        ),
    ]
