# Generated by Django 3.0 on 2021-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0006_auto_20210701_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_stops',
            name='stop_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bus_stops',
            name='stop_lon',
            field=models.FloatField(),
        ),
    ]
