# Generated by Django 3.0 on 2021-07-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinBus', '0007_auto_20210701_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bus_stops',
            new_name='BusStops',
        ),
    ]
