# Generated by Django 3.0 on 2021-07-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='leap_card',
            field=models.BooleanField(null=True),
        ),
    ]
